Issue #423 Solved  -> Dynamically generating colors of all the lables…
GoogleChromeLabs/ProjectVisBug pull request #479
Opened 2020-11-24 15:01 UTC by aashu0148

… in /zindex plugin are now maintaine their legibility contrast and are easily visible

2020-11-24 15:04 UTC, aashu0148 commented
@googlebot I signed it!

2020-11-24 23:03 UTC, argyleink commented
it is significantly improved! great work 👍 

there are still 1/15 or so that fail, any thoughts on why or if you could tweak it to be even more conservative? 

![Screen Shot 2020-11-24 at 2 58 46 PM](https://user-images.githubusercontent.com/1134620/100161115-b0570680-2e65-11eb-9951-780d8af1ce2c.png)
![Screen Shot 2020-11-24 at 2 58 52 PM](https://user-images.githubusercontent.com/1134620/100161117-b0ef9d00-2e65-11eb-851d-7948ee8c179c.png)

maybe switch to hsl to rotate the hue for randomization? 
or create a "safe palette" of like 50 colors and randomly pick one?

2020-11-25 08:57 UTC, aashu0148 commented
> it is significantly improved! great work 👍
> 
> there are still 1/15 or so that fail, any thoughts on why or if you could tweak it to be even more conservative?
> 
> ![Screen Shot 2020-11-24 at 2 58 46 PM](https://user-images.githubusercontent.com/1134620/100161115-b0570680-2e65-11eb-9951-780d8af1ce2c.png)
> ![Screen Shot 2020-11-24 at 2 58 52 PM](https://user-images.githubusercontent.com/1134620/100161117-b0ef9d00-2e65-11eb-851d-7948ee8c179c.png)
> 
> maybe switch to hsl to rotate the hue for randomization?
> or create a "safe palette" of like 50 colors and randomly pick one?

okay @argyleink  I'll modify the colors to be more darker.

2020-11-25 08:59 UTC, aashu0148 commented
so @argyleink should i close this pull request and make a new one.

2020-11-25 09:16 UTC, aashu0148 commented
hey @argyleink  please review it. Now I have made all the colors little bit darker.

2020-11-30 18:45 UTC, argyleink commented
Gave it a nice look and review today! 

I was able to find labels quickly that didn't pass the contrast ratio scores.. I tried tweaking your numbers in the code here and there to see if a healthy value showed up, but it felt like it was ruining the value of the different colors, like they were merging towards middle ranges. 

I think we need to stop "randomly" making colors, hoping they pass. Here's 2 ideas forward: 
1. create ~25 colors we think provide enough differentiation and will contrast well with white, then pick randomly from that set.
1. import the tiny color library that visbug uses to modify and inspect colors. use this library to create random colors and test them for passing ratios. run this in a loop so it always returns a random, valid contrast passing label background color.

1 is simpler and static. 2 would be trickier but more dynamic. thoughts?

2020-11-30 18:46 UTC, argyleink requested changes
to close the ticket with confidence, we need to always create readable labels

2020-12-01 13:26 UTC, aashu0148 commented
> Gave it a nice look and review today!
> 
> I was able to find labels quickly that didn't pass the contrast ratio scores.. I tried tweaking your numbers in the code here and there to see if a healthy value showed up, but it felt like it was ruining the value of the different colors, like they were merging towards middle ranges.
> 
> I think we need to stop "randomly" making colors, hoping they pass. Here's 2 ideas forward:
> 
> 1. create ~25 colors we think provide enough differentiation and will contrast well with white, then pick randomly from that set.
> 2. import the tiny color library that visbug uses to modify and inspect colors. use this library to create random colors and test them for passing ratios. run this in a loop so it always returns a random, valid contrast passing label background color.
> 
> 1 is simpler and static. 2 would be trickier but more dynamic. thoughts?

okay @argyleink  i will check try both ways and update you with suitable one.

2020-12-01 13:34 UTC, aashu0148 commented
hey @argyleink where do i find tiny color library ??

2020-12-01 13:53 UTC, aashu0148 commented
> Gave it a nice look and review today!
> 
> I was able to find labels quickly that didn't pass the contrast ratio scores.. I tried tweaking your numbers in the code here and there to see if a healthy value showed up, but it felt like it was ruining the value of the different colors, like they were merging towards middle ranges.
> 
> I think we need to stop "randomly" making colors, hoping they pass. Here's 2 ideas forward:
> 
> 1. create ~25 colors we think provide enough differentiation and will contrast well with white, then pick randomly from that set.
> 2. import the tiny color library that visbug uses to modify and inspect colors. use this library to create random colors and test them for passing ratios. run this in a loop so it always returns a random, valid contrast passing label background color.
> 
> 1 is simpler and static. 2 would be trickier but more dynamic. thoughts?

hey @argyleink I have applied method 1 to it. Added a array of 25 colors and then randomly choosing a color from it.
Please check this :)

2020-12-01 19:20 UTC, argyleink approved these changes
There were still some colors that didn't pass the contrast ratios, I've updated them 👍🏻  That puts this PR into a ready state!

2020-12-01 19:20 UTC, argyleink commented on app/plugins/zindex.js
> +            const colors = ["#eb4034", "#68eb34", "#34a5eb", "#4334eb", "#b134eb", "#eb34a2", "#eb3446", "#8f2e2b", , "#8f692b", "#8a8f2b", "#358f2b", "#2b8f82", "#2b678f", "#2b2b8f", "#8f2b8f", "#8f
```suggestion
            const colors = ["#eb4034", "#30850f", "#116da7", "#4334eb", "#b134eb", "#df168e", "#e8172c", "#8f2e2b", "#8f692b", "#8a8f2b", "#358f2b", "#2b8f82", "#2b678f", "#2b2b8f", "#8f2b8f", "#8f2b55", "#1eff00", "#a86800", "#ff0000", "#008035", "#0026ff", "#bb00ff", "#d600b6", "#e60067", "#137878"];
```

2020-12-01 19:21 UTC, merged

2020-12-01 19:21 UTC, argyleink commented
fixes #423

2020-12-01 19:22 UTC, argyleink commented
nice work, thank you @aashu0148 💯

2020-12-02 03:50 UTC, aashu0148 commented
> nice work, thank you @aashu0148 💯 

Please tell me if anything more to do.... I will love to contribute to visbug😊

2020-12-02 16:13 UTC, argyleink commented
Here's a list of [good first issues](https://github.com/GoogleChromeLabs/ProjectVisBug/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue+%F0%9F%91%8D%22) if you're looking for low hanging fruit!

There's also this one which could be nice and swift to work on https://github.com/GoogleChromeLabs/ProjectVisBug/issues/389, which the code is pretty straight forward but testing it may be difficult if you dont have windows/linux readily available.

There's also room for writing more tests. So if you're interested in unit or e2e tests, you could write some of those for practice/learning/helping. 

🙂